  services:
    app:
      build: .
      ports:
        - "7777:7777"
      volumes:
        - .:/usr/src/app
        - node_modules:/usr/src/app/node_modules
      environment:
        NODE_ENV: development
        PORT: 7777
        JWT_SECRET: thisIsMySecretMessagingAppKey
      depends_on:
        - db
      command: npm run prod
      restart: unless-stopped
    db:
      image: postgres:15-alpine
      restart: always
      environment:
        POSTGRES_USER: user123
        POSTGRES_PASSWORD: password123
        POSTGRES_DB: db123
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
        
  volumes:
    node_modules:
    pgdata: